### ISSUE TITLE
Documation clarification.

### ISSUE THREAD

**Issue by demaree** [hivemq/hivemq-prometheus-extension#8]
**What did you do?**

Followed the install instructions located here:
( https://www.hivemq.com/extension/prometheus-extension/ )

**What did you expect to see?**

To see metrics located here http://xx.xx.xx.xx:9090/targets
This is my prometheus server and config for it. I get back this error.
"Get http://xx.xxxx.xx:9399/metrics: dial tcp xx.xx.xx.xx:9399: connect: connection refused"

Prometheus configuration file:
```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
- job_name: hivemq
  - targets:
    - 'xx.xx.xx.xx:9399'
```

I am wondering if I have the .jar file in the right location? my hivemq lives in /opt/hivemq, but I couldn't find the /extensions directory. There was a /plugins directory and I tried that both putting the .jar file directly into it and also putting the 'hivemq-prometheus-extension' directory into the plugins directory. I was hoping for some clarification.

**Comment by MicWalter** [comment]
Hi demaree,

are you using a HiveMQ 3 or HiveMQ 4 broker, as you can see a plugin folder it seems you are using HiveMQ 3?
For HiveMQ 3 you will need the Prometheus plugin: https://github.com/hivemq/prometheus-monitoring-plugin, the extension does not work with HiveMQ 3.

What I can already see is that the configured endpoint is wrong, you need to add the **metrics_path** to your prometheus.yml, because by default Prometheus tries to crap metrics from path **/metrics** and the targets should have the correct port (9090 instead of 9399).

```
global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
- job_name: hivemq
  metrics_path: '/targets'
  - targets:
    - 'xx.xx.xx.xx:9090'
```

_A tip for checking if the plugin/extension is configured correctly:_
Open http://xx.xx.xx.xx:9090/targets with a browser, if you see a list of metrics you have correctly configured the plugin/extension.

If you still have problems please also provide the **prometheusConfiguration.properties** and the HiveMQ logs (/opt/hivemq/logs/hivemq.log).


Kind regards,
Michael

**Comment by demaree** [comment]
That explains it. Yes, I'm using HiveMQ 3. Is there a binary package for the plugin version? I appreciate your help Michael, I would have been super lost.

**Comment by MicWalter** [comment]
Hi demaree,

afaik there is no binary package available anymore, but you can build it yourself quite easily.

- clone the linked prometheus plugin project 
- change to the root path of the project
- type "mvn package" into the terminal
- in the target folder of the project you find the zip file (hivemq-prometheus-monitoring-plugin-1.0.0-distribution.zip)

Or if you trust me:
[hivemq-prometheus-monitoring-plugin-1.0.0-distribution.zip](https://github.com/hivemq/hivemq-prometheus-extension/files/3818538/hivemq-prometheus-monitoring-plugin-1.0.0-distribution.zip)

Kind regards,
Michael

**Comment by demaree** [comment]
Thank you again Michael, that is exactly what I was looking for. I Just set up the dashboard in Grafana and it looks amazing. I appreciate you taking the time to help me with this issue.
